### ISSUE TITLE
How Does This Plugin Resolve `javac`?

### ISSUE THREAD

**Issue by kevinmeredith** [davidB/scala-maven-plugin#161]
Recently I encountered an error my CI server with: 

`[com.myproject.blah] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.6:compile (scala-compile-first) on project model: wrap: java.io.IOException: Cannot run program "javac": error=2, No such file or directory`

How does this plugin find `javac` for compilation?

`JAVA_HOME` or `PATH`?

Also, why does it need `javac`?

**Comment by srowen** [comment]
FWIW I'm finding that 3.3.1 won't work with, for example, the Apache Spark build when zinc is enabled. 3.2.2 does. as far as I can tell, it's because it now tries to find `javac` by searching `java.home` first. But this points to a JRE directory in my local (Mac) and Jenkins (Linux) environments when Java runs.

**Comment by davidB** [comment]
Thanks for reporting

**Comment by slandelle** [comment]
> Also, why does it need javac?

`scalac` doesn't compile java code. It merely parses it for types and signatures. It relies on javac for doing the actual compilation.

**Comment by slandelle** [comment]
Fixed along #403
