### ISSUE TITLE
Issues with mixed Scala and Java project when using Lombok.

### ISSUE THREAD

**Issue by vilu** [davidB/scala-maven-plugin#288]
I have a project where a library seems to be using Lombok. Depending on this from Scala sources has proven impossible, I get compilation issues complaining of missing symbols (of getters and setters generated with annotations). The project compiles if I reference the library from Java source files. I have tried to change the compilation order https://davidb.github.io/scala-maven-plugin/example_incremental.html (JavaThenScala) with no real improvement. 

Any ideas?

**Comment by davidB** [comment]
iirc, the incremental compiler could not work in this case because scalac and the incremental compiler used the java source, not the .class.
The alternatives I could see were:
- to setup compilation of scala after java compilation
- to unmixe the project, one for java, one for scala (with dependencies to the java one)
- to migrate .java with lombok into scala (iirc, nearly every feature of lombok are available in scala, at least the sugar syntax for stupid getter/setter)

**Comment by slandelle** [comment]
I don't think what you're trying to do has a chance to work.
`JavaThenScala` compile order means the scala compiler will first take care of compiling Java code to generated bytecode is added to the classpath so then Scala code can be compiled against it.
Still, I don't think Lombox has no chance to plug in.

If you really want to mix Lombok and Scala in the same project, you might want to have separate maven modules: one with Lombok and one with Scala.

**Comment by sxp** [comment]
Lombok has a plugin("lombok-maven-plugin") can generate java source to "target/generated-sources/delombok", but scala-maven-plugin can't separately config Java source dir.  So when using scala-maven-plugin after lombok-maven-plugin,  got "XXXX is already defined as class XXXX" error, all java classes had been duplicated.
