### ISSUE TITLE
incremental mode pick Zinc version against target compiled version, not current runtime one

### ISSUE THREAD

**Issue by slandelle** [davidB/scala-maven-plugin#327]

**Comment by slandelle** [comment]
Closed by a19fa5e5072893035a573162846a271ec794f8a4

**Comment by slandelle** [comment]
@davidB Because of this, 4.0.0 can't compile 2.11 project. Do you want to release 4.0.1?

**Comment by davidB** [comment]
With the fix can the plugin compile 2.11 ?
If "incremental" mode is restricted to some version of scala, maybe we should fallback to "all" mode (with a warning in log) for incompatible scala version ?

**Comment by slandelle** [comment]
> With the fix can the plugin compile 2.11 ?

Yes

> If "incremental" mode is restricted to some version of scala, maybe we should fallback to "all" mode (with a warning in log) for incompatible scala version ?

Not sure it's worth it. I've very surprised that someone is using maven with Scala 2.13 milestones and it's most likely not for a production project.

**Comment by davidB** [comment]
With 4.0.0 what is the minimal scala version supported 2.11, 2.10 or 2.9 ?

**Comment by slandelle** [comment]
Oh right, there's indeed a limit because I use the precompiled `compiler-bridge` artifacts to speed up first time compilation. Those are only available for Scala 2.10+.

Is it an issue? IMHO, it's fine to drop support for Scala 2.9.

**Comment by SethTisue** [comment]
dropping support for 2.9 is a no-brainer IMO, it's been forever since I've heard of anybody using 2.9 for any reason

but also, fwiw, I would also encourage you to drop 2.10 support. (I go around and say the same thing in all of the Scala OSS repositories.) _especially_ since you're doing a big, major version bump

if anyone has the misfortune to still be stuck on Scala 2.10 at this point (this is increasingly uncommon, especially now that sbt 1 is well-established and the sbt 0.13.x series is EOL), surely they can cope with continuing to use the old version of the plugin.

**Comment by slandelle** [comment]
@SethTisue There's no special code dedicated to Scala 2.10, we just depend on sbt/zinc to do the job. I guess Scala 2.10 support will get dropped de facto when we'll be upgrading to a zinc version that no longer supports it, most likely when there will be a new version supporting Scala 2.13.

**Comment by davidB** [comment]
Ok, so I'll release 4.0.1 during the week.
