### ISSUE TITLE
Issue with brand new Scala 2.13

### ISSUE THREAD

**Issue by ilaborie** [davidB/scala-maven-plugin#346]
I've update my benchmark project to compare the new `LazyList` vs the old `Stream`, here: <https://github.com/ilaborie/refactorLoops/tree/master/samples-scala>

But I cannot compile the scala part :

```maven
[INFO] --- scala-maven-plugin:4.0.2:compile (default) @ samples-scala ---
[WARNING] Scala library detected 2.13.0 doesn't match scala.compat.version : 2.12.-1
[WARNING]  Expected all dependencies to require Scala version: 2.12.-1
[WARNING]  io.github.ilaborie:samples-scala:1.0-SNAPSHOT requires scala version: 2.13.0
[WARNING] Multiple versions of scala libraries detected!
[INFO] Using incremental compilation using Mixed compile order
[INFO] Compiling 2 Scala sources to /Users/igorlaborie/Documents/Workspaces/playground/refactorLoops/samples-scala/target/classes ...
[ERROR] ## Exception when compiling 2 sources to /Users/igorlaborie/Documents/Workspaces/playground/refactorLoops/samples-scala/target/classes
scala/collection/GenTraversableOnce
xsbt.CompilerInterface.newCompiler(CompilerInterface.scala:22)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:134)
sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:121)
sbt.internal.inc.FreshCompilerCache.apply(CompilerCache.scala:78)
sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:88)
sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
sbt_inc.SbtIncrementalCompiler.compile(SbtIncrementalCompiler.java:127)
scala_maven.ScalaCompilerSupport.incrementalCompile(ScalaCompilerSupport.java:284)
scala_maven.ScalaCompilerSupport.compile(ScalaCompilerSupport.java:101)
scala_maven.ScalaCompilerSupport.doExecute(ScalaCompilerSupport.java:83)
scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:555)
org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:566)
org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

**Comment by davidB** [comment]
As a workaround, I suggest you:
- to set scala.compat.version to 2.13 or to remove it (as you don't use it)
- to no use the incremental mode (default since scala-maven-plugin 4) `<recompileMode>all<recompileMode>`

**Comment by slandelle** [comment]
@jvican Would you have any clue, please? I'm at a loss here.

**Comment by ilaborie** [comment]
@davidB  The workaround works pretty well, Thanks !

**Comment by isomarcte** [comment]
@slandelle @davidB this is likely because we are mixing 2.12 and 2.13 classpaths right now. `scala-maven-plugin` depends on `zinc_2.12`, but dynamically pulls in the `compiler-bridge` for the current Scala version, in this case 2.13.

However, while there _is_ a version of `compiler-bridge` published for 2.13, there are not 2.13 artifacts for the rest of the zinc project for some reason.

**Comment by slandelle** [comment]
Back in the Zinc 0.3.15 days, we used to pass sbt-interface and compiler-interface sources in order to compile the correct bridge. We could run zinc with Scala 2.10 and compile code in Scala 2.11 and 2.12 with no issue.

Now that we've upgraded to Zinc 1, it seems there something broken and maybe we didn't notice because Scala 2.11 and 2.12 were compatible wrt compiler-bridge.

Now, I realize I don't get how compiler-bridge is supposed to work. I would expect the version to be a combo of (Scala runtime version, Scala compiler version) but it's just a single one...

**Comment by isomarcte** [comment]
@slandelle I think we may want to consider just runtime loading the full set of correct jars. We already do that for some stuff, like `jline`.

I'd be happy to take a look at it if no one has any objections/better ideas.

**Comment by slandelle** [comment]
> I think we may want to consider just runtime loading the full set of correct jars.

That's what we do, or at least supposed to.

Now, what I realize I don't get is the difference between on-the-fly compiled compiler-bridge and precompiled one.

- The former is compiled on the fly by sbt and account for the runtime Scala version and the target compiler version, eg `org.scala-sbt-compiler-bridge_2.12-1.2.5-bin_2.12.8__55.0.jar`
- The latter is published on [maven central](https://search.maven.org/search?q=g:org.scala-sbt%20AND%20a:compiler-bridge_2.12&core=gav) and only has one single version

So I realize I don't understand what the latter is. Why does it only have one single version? I thought it meant it's both compiled against, and aiming at a given major version. But then, I really don't understand why it fails to load properly:

* from our [SbtIncrementalCompiler](https://github.com/davidB/scala-maven-plugin/blob/master/src/main/java/sbt_inc/SbtIncrementalCompiler.java#L53), loader has the Scala 2.13 jars
* Zinc's [AnalyzingCompiler](https://github.com/sbt/zinc/blob/develop/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/AnalyzingCompiler.scala#L262-L264) is supposed to use this ClassLoader to load the compiler.

@jvican @eed3si9n @dwijnand Could you guys provide any clue on what's going on, please?

**Comment by slandelle** [comment]
@isomarcte Sure, feel free to give it a try.

**Comment by eed3si9n** [comment]
Using Zinc 1.2.5 as example, there's a code here https://github.com/sbt/zinc/blob/v1.2.5/internal/zinc-ivy-integration/src/main/scala/sbt/internal/inc/ZincComponentCompiler.scala#L40-L58 that tries to locate the compiler bridge source module.

```scala
  private[sbt] def getDefaultBridgeModule(scalaVersion: String): ModuleID = {
    def compilerBridgeId(scalaVersion: String) = {
      scalaVersion match {
        case sc if (sc startsWith "2.10.")       => "compiler-bridge_2.10"
        case sc if (sc startsWith "2.11.")       => "compiler-bridge_2.11"
        case sc if (sc startsWith "2.12.")       => "compiler-bridge_2.12"
        case "2.13.0-M1"                         => "compiler-bridge_2.12"
        case sc if (sc startsWith "2.13.0-pre-") => "compiler-bridge_2.13.0-M2"
        case sc if (sc startsWith "2.13.0-M")    => "compiler-bridge_2.13.0-M2"
        case sc if (sc startsWith "2.13.0-RC")   => "compiler-bridge_2.13.0-M2"
        case _                                   => "compiler-bridge_2.13"
      }
    }
    import xsbti.ArtifactInfo.SbtOrganization
    val bridgeId = compilerBridgeId(scalaVersion)
    ModuleID(SbtOrganization, bridgeId, incrementalVersion)
      .withConfigurations(CompileConf)
      .sources()
  }
```

(In 1.3.x this moved to https://github.com/sbt/sbt/blob/v1.3.0-RC2/zinc-lm-integration/src/main/scala/sbt/internal/inc/ZincComponentCompiler.scala.)

In 1.2.5, there is a way to then compile the compiler bridge from source https://github.com/sbt/zinc/blob/v1.2.5/zinc/src/main/scala/sbt/internal/inc/ZincUtil.scala#L85-L95.
This mechanism allows us to use Zinc 1.2.5 (that came out in Dec, 2018) to compile Scala 2.13.0 that came out last Friday even though the Scala compiler has changed its internal API. If you see the publish date of https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.13/1.2.5/, you'd notice it's 2019-06-07.

Unlike Scala Library, there's no binary compatibility guarantees for Scala Compiler, so please ignore the binary artifact `compiler-bridge_2.13-1.2.5.jar`, and use `compiler-bridge_2.13-1.2.5-sources.jar`. 

Side note: Notable exception to this rule is Dotty, since Dotty actually creates its own compiler bridge binary. In the long term, that's likely a saner way of dealing with this situation, so I am planning to do that for Scala 2.x as well (see https://github.com/sbt/zinc/pull/661).

**Comment by slandelle** [comment]
Thanks a lot for your detailed explanations, @eed3si9n !

**Comment by rvamiracle** [comment]
> As a workaround, I suggest you:
> 
> * to set scala.compat.version to 2.13 or to remove it (as you don't use it)
> * to not use the incremental mode (default since scala-maven-plugin 4) `<recompileMode>all<recompileMode>`

This workaround seem to break tests with mixed Scala and Java code. Scala tests cannot use Java classes, and Java tests cannot use Scala classes.

**Comment by davidB** [comment]
@rvamiracle I didn't test mixed with test (I'll add a test under it for your use case, after my biz trip), but mixed in main work with recompileMode define as properties:
```xml
<configuration>
                  <properties>
                    <scala.version>2.13.0</scala.version>
                    <scala.compat.version>2.13</scala.compat.version>
                    <recompileMode>incremental</recompileMode>
                  </properties>
```

**Comment by rvamiracle** [comment]
Hmmm, adding this missing piece to the maven-compiler-plugin fixes the issue with mixed source code. This only works with recompileMode=all still.
```
<executions>
	<execution>
		<phase>compile</phase>
		<goals>
			<goal>compile</goal>
		</goals>
	</execution>
</executions>
```
For reference, here is the total plugin config for maven-compiler-plugin:
```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>3.8.0</version>
	<configuration>
		<source>1.8</source>
		<target>1.8</target>
	</configuration>
	<executions>
		<execution>
			<phase>compile</phase>
			<goals>
				<goal>compile</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

**Comment by slandelle** [comment]
@eed3si9n How did you build the [compiler-bridge_2.13-1.2.5](https://search.maven.org/artifact/org.scala-sbt/compiler-bridge_2.13/1.2.5/jar) jar that's on maven central exactly?

The [1.2.5 tag builds against 2.13.0-M2](https://github.com/sbt/zinc/blob/v1.2.5/project/Dependencies.scala#L8) (pretty expected as it was release before Scala 2.13.0).

I have a local branch (not pushed yet, needs some clean up) that compiles the compiler-bridge jar from sources on the fly instead of fetching the pre-compiled binary from central.
It works just fine with the above sample projet, so I suspect the jar in maven central is actually broken and that it contains code that requires `scala.collection.GenTraversableOnce`, hence the ClassNotFoundException.

**Comment by eed3si9n** [comment]
@slandelle I think I just set the version, and published, so if the build is set up with 2.13.0-M2, it's entirely possible that I published the binary using that since sbt recompiles compiler bridge source, it didn't occur to me that someone could be relying on the binary. Zinc 1.3.0 once it comes out will use Scala 2.13.0.

**Comment by slandelle** [comment]
Thanks for your feedback!

> it didn't occur to me that someone could be relying on the binary

I suspect I'm the only one (meaning Gatling bundle and now scala-maven-plugin) 😄

Now, the precompiled bridge sure has some pros: faster first compilation (bridge is already compiled) and no additional special install (would have to introduce something similar to `~/.sbt/boot/`).

> Zinc 1.3.0 once it comes out will use Scala 2.13.0.

Do you have any ETA yet?

**Comment by eed3si9n** [comment]
> Do you have any ETA yet?

No, but https://github.com/sbt/zinc/releases/tag/v1.3.0-M7 is available, which I think uses Scala 2.13.0.

**Comment by slandelle** [comment]
Thanks @eed3si9n , upgrading to 1.3.0-M7 indeed fixed the problem.

**Comment by isomarcte** [comment]
Thanks for taking care of this @slandelle, sorry I didn't get a chance to look at it in the last week.

**Comment by slandelle** [comment]
WARNING: latest Zinc crashes on 32 bits env, see https://github.com/sbt/sbt/issues/4841
