### ISSUE TITLE
Maven version requirement

### ISSUE THREAD

**Issue by tmetzke** [davidB/scala-maven-plugin#429]
Hi David,

We would love to integrate the plugin into our project. However, in our very specific case, moving to a Maven version higher than 3.2.5 would mean a lot of effort at the moment due to several unresolved regressions ([MSHADE-206](https://issues.apache.org/jira/browse/MSHADE-206), [MNG-5899](https://issues.apache.org/jira/browse/MNG-5899)).

Based on https://github.com/davidB/scala-maven-plugin/issues/292, the minimal Maven version forced upon users to run the plugin is 3.3.9. This seems to be a rather random choice from what I can see. Are there any special requirements the plugin has that would justify a version requirement above Maven 3.0?

We would love to see this requirement loosened up a bit to be more inclusive.

Best,
Tobias

**Comment by slandelle** [comment]
Current maven version is 3.6.2.
Maven 3.3.9 was released in late 2015: 5 years ago!
If you check #292 , you'll see that I mentioned it was the version available with Debian stable back then.

The wider the compatibility range, the greater the risk of incompatibility and the maintenance burden.
I don't remember the details, but I think we need a version of plexus that's more recent than the one in maven 3.0.

Have you tried contributing fixes to the issues you've mentioned above? Also, work on maven 4 has started, so you might want to reach out to the maven people about those issues. Try Twitter, eg Robert Scholte, if you can't get attention on Jira.

Honestly, I don't feel like trying to support versions that are more than 5 years old, nor handling an extra burden because someone else has broken something. Upstream fixes are way better than downstream workarounds.
