### ISSUE TITLE
Not support java 16 record

### ISSUE THREAD

**Issue by cmonkey** [davidB/scala-maven-plugin#521]
alchim31 scala plugin version : 4.5.3 
java version 16
recompileMode = incremental 
compileOrder = Mixed 

ca Example.java 
record Example(int id, double amount){}

compile failed : illegal start of type declaration

**Comment by slandelle** [comment]
Please provide a sample project and push it on github.

**Comment by slandelle** [comment]
Thx.

The Scala compiler doesn't support Java records yet.
According to https://github.com/scala/bug/issues/11908, support should land in 2.13.7, which hasn't been released yet.
According to [this ticket](https://contributors.scala-lang.org/t/scala-2-13-7-release-planning/5221/2), the ETA is beginning of November.

Anyway, closing as the issue is not in this plugin.

**Comment by EleanoraKotarski1968** [comment]
Same thing here

**Comment by slandelle** [comment]
Scala 2.13.7 was just released today. Try upgrading.
